In [ ]:
import numpy as np 

In [ ]:
Data = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
Data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
Array = np.array(Data)
Array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
Array[2]

array([7, 8, 9])

In [24]:
Array[2,0]

np.int64(7)

In [28]:
Array[0,0]

np.int64(1)

Arange fonksiyonu, verdiğiniz 2 sayı arasını Array’e çevirir.

In [31]:
np.arange(0,56)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [41]:
np.arange(0,57,8)


array([ 0,  8, 16, 24, 32, 40, 48, 56])

Zeros Fonksiyonu, belirttiğiniz miktar kadar 0'lardan oluşan bir Array yaratacaktır.

In [44]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Ones Fonksiyonu, belirttiğiniz miktar kadar 1'lerden oluşan bir Array oluşturacaktır.



In [49]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
np.ones((25,4))
#bu şekilde yazarak istediğimiz matrisi oluşturabiliyorum artı olarak zerodtada geçerli

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

eye fonksiyonu çapraz matris oluştur.0 ve 1 lerden oluşur ve 1 ler sol üst köşeden sağ alt köşeye doğru yerleşir

In [60]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Linspace Fonskiyonu genel olarak 3 değer alır. İlk 2 değer arasında olan sayıları 3. sayıya eşit olarak dağıtır.

In [66]:
np.linspace(0,100,5)
#0 ve 100 arasını 5 ölçeğe ayırdı

array([  0.,  25.,  50.,  75., 100.])

In [70]:
np.linspace(0,30,3)

array([ 0., 15., 30.])

Random fonksiyonları

Random.Randint fonksiyonu girilen 2 değer arasında rastgele 2 değer üretir .Parantez içine girilen 3. sayı ise kaç tane rastgele sayı istediğini belirtir

In [75]:
np.random.randint(100,200)

105

In [77]:
np.random.randint(10,50,5)

array([22, 33, 24, 46, 13], dtype=int32)

In [98]:

np.random.rand(10)

array([0.69510446, 0.48284575, 0.234305  , 0.32658616, 0.33208841,
       0.29881856, 0.17620912, 0.19470012, 0.32745002, 0.76153738])

Random.randn fonksiyonu -1 ve 1 arasındaki rastgele değerleri çağırır parantezin içine yazılacak değer kaç tane değer istediğimiz olur

In [94]:
np.random.randn(100)

array([-0.33039893, -1.29804397,  1.1716307 ,  0.42438677,  0.93336486,
        1.36877139, -0.6120802 ,  1.85132569,  1.02378242, -1.12154553,
       -2.72900067, -0.38644485, -0.09396727,  1.47614739,  0.84523126,
        0.28780744, -0.14427066, -0.56295394, -0.89847295,  1.79230474,
       -0.37285402,  0.40238966,  0.08439791, -2.1428713 ,  0.84124582,
        0.35205813, -1.45669533,  2.4145798 ,  0.05223175,  0.04610375,
       -0.22507922, -1.09954064,  1.12944686,  0.73474836,  0.7269676 ,
        0.16188519,  0.41903851, -1.02464903,  0.7765404 ,  0.57051945,
       -0.35092812,  1.47091584,  0.55011084,  1.47326968,  0.55521343,
       -1.03802102, -0.54287604,  0.98525315, -2.20082241, -0.47133076,
       -0.58234317, -1.16160373,  0.07047075, -1.01090958, -1.41211486,
       -0.20286892, -0.07588904, -0.69088096,  1.21954203, -1.13281206,
       -0.84723281,  0.06892925,  1.99254302, -0.10919112, -1.00864856,
       -0.15612518, -2.47398056, -1.22736682,  0.54408977, -0.53

In [112]:
data1= np.arange(36)
data1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

reshape fonksiyonu matrisi şekillendirir

In [118]:
data1.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [121]:
data1.reshape(4,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

cumsum fonksiyonu kümülatif olarak toplar.Asağıdaki örnekte artış miktari birer birer artmıştır

In [133]:
data1.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325,
       351, 378, 406, 435, 465, 496, 528, 561, 595, 630])

argmax kısaca en büyük değere sahip değerin indexsini verir

In [143]:
data1.argmax()

np.int64(35)

argmin() de aynı mantık üzerine kurulu sadece en düşük değeri verecektir.

In [157]:
data1.argmin()

np.int64(0)

np.linalg.det() arrayin determinantını almay yarar

In [162]:
data2 = np.array([[1,2],[3,4]])
np.linalg.det(data2)

np.float64(-2.0000000000000004)

np.std() standart sapmayı bbulur

In [172]:
np.std(data1)

np.float64(10.388294694831615)

In [180]:
data3 = np.arange(0,100)
data3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [186]:
data3[:6]
#:x ifadesinie girilen değere kadar olan değeri bastırır

array([0, 1, 2, 3, 4, 5])

In [190]:
data3[::10]
#::X x ifadesi kadar atlanarak bastırır

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [194]:
data3>40
#verilen ifadenin dopruluk değerini tek tek karşılaştırarak true false verir

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [200]:
array1 = np.array([1,2,3,4,5,6])
array2 = np.array([7,8,9,10,11,12])


In [202]:
array1+array2

array([ 8, 10, 12, 14, 16, 18])

In [204]:
array1-array2

array([-6, -6, -6, -6, -6, -6])

In [206]:
array1*array2

array([ 7, 16, 27, 40, 55, 72])

In [210]:
array2/array1

array([7. , 4. , 3. , 2.5, 2.2, 2. ])

In [212]:
array1**array2

array([         1,        256,      19683,    1048576,   48828125,
       2176782336])

In [214]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])